version: '2'
services:
    appnav-app:
        image: appnav
        external_links:
            - appnav-mysql:mysql
            - appnav-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/appnav?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    appnav-mysql:
        extends:
            file: mysql.yml
            service: appnav-mysql
    appnav-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: appnav-elasticsearch
